extensions:
  toppg:
    enabled: false
  ping:
    enabled: true
  branding:
    enabled: false
  nice_errors:
    enabled: true
  help:
    enabled: false
  add-dm:
    enabled: false
  welcome:
    enabled: true
    debug: false
    channel_id: 950791407243776023
    message: "Hey {mention}, bienvenue sur le discord {server} ğŸ‰ğŸ¤— ! passe lire le <#123456789123456> avant de t'amuser ici !! Passe par <#123456789123456>  et <#123456789123456> aussi pour t'y retrouver !"

bot:
  slash:
    enabled: true

use:
  bot: true
  backend: false
