# Copyright (c) CommunautÃ© Les FrÃ¨res Poulain
# SPDX-License-Identifier: MIT

extensions:
  toppg:
    enabled: false
  ping:
    enabled: true
  branding:
    enabled: false
  nice_errors:
    enabled: true
  help:
    enabled: false
  add-dm:
    enabled: false
  welcome:
    enabled: true
    channel_id: 563776770210398212
    message: "Hey {mention}, bienvenue sur le discord {server} ğŸ‰ğŸ¤— ! passe lire le <#563836837043372033> avant de t'amuser ici !! Passe par <#763454034203377745>  et <#697045814450585620> aussi pour t'y retrouver !"

bot:
  slash:
    enabled: true

use:
  bot: true
  backend: false
