# Copyright (c) NiceBots.xyz
# SPDX-License-Identifier: MIT

extensions:
  topgg:
    enabled: false
  ping:
    enabled: true
  branding:
    enabled: false
  nice_errors:
    enabled: true
  help:
    enabled: false
  add-dm:
    enabled: false
  afk_notification:
    enabled: true
    start_time: "15:12"
    stop_time: "06:00"
    afk_reminder_every: 60
    afk_reminder_timeout: 15

bot:
  slash:
    enabled: true
use:
  bot: true
  backend: false
