# Copyright (c) NiceBots.xyz, CommunautÃ© Les FrÃ¨res Poulain
# SPDX-License-Identifier: MIT

extensions:
  topgg:
    enabled: false
  ping:
    enabled: true
  branding:
    enabled: false
  nice_errors:
    enabled: true
  help:
    enabled: false
  add-dm:
    enabled: false
  afk_notification:
    enabled: true
    start_time: "22:00"
    stop_time: "06:00"
    afk_reminder_every: 60
    afk_reminder_timeout: 15
    logs_channel_id: 573224892930064394
  welcome:
    enabled: true
    channel_id: 563776770210398212
    message: "Hey {mention}, bienvenue sur le discord **{server}** ðŸŽ‰ðŸ¤— ! Passe lire le <#563836837043372033> avant de t'amuser ici !! Passe par <#763454034203377745>  et <#697045814450585620> aussi pour t'y retrouver !"

bot:
  slash:
    enabled: true

use:
  bot: true
  backend: false
